config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:email',     to: 'users#show',       via: 'get'

  resources :member_groups
  resources :user_groups
  resources :user_access_audit_logs
  resources :teics_audit_logs
  resources :roles
  resources :store_accesses
  resources :cert_source_links
  resources :user_source_links
  resources :user_store_roles
  resources :cert_store_roles
  resources :user_stores
  resources :cert_stores
  resources :identity_types
  resources :environments
  resources :source_links
  resources :sources
  resources :home
  resources :welcome

   root 'home#index'

end

app/models/cert_source_link.rb
class CertSourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source_link
  belongs_to :cert_store
  belongs_to :user_group

end

app/models/cert_store.rb
class CertStore < ActiveRecord::Base
  mount_uploader :unc, UncUploader
  acts_as_paranoid

  belongs_to :source
  belongs_to :environment
  belongs_to :identity_type
  belongs_to :user_group
  has_many :cert_source_links
  has_many :cert_store_roles

  validates :CertStoreName, :CertStoreDescription, :CertStorePassword, :CertStoreExpirationDate, :unc, :MimeType, :source_id, :environment_id, :identity_type_id, presence: true

  accepts_nested_attributes_for :cert_source_links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :cert_store_roles, reject_if: :all_blank, allow_destroy: true


end

app/models/cert_store_role.rb
class CertStoreRole < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role
  belongs_to :cert_store
  belongs_to :user_group

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :EnvironmentName, :EnvironmentDescription, presence: true

end

app/models/identity_type.rb
class IdentityType < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :IdentityTypeName, :IdentityTypeDescription, presence: true

end

app/models/member_group.rb
class MemberGroup < SecondBase::Base
  acts_as_paranoid

  belongs_to :user_group
  belongs_to :user

end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source
  belongs_to :user_group
  has_many :cert_store_roles
  has_many :user_store_roles

  validates :RoleDescription, :source_id, presence: true

end

app/models/source.rb
class Source < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :SourceDescription, presence: true

end

app/models/source_link.rb
class SourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_source_links
  has_many :user_source_links

  validates :Hyperlink, presence: true

end

app/models/store_access.rb
class StoreAccess < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_store
  belongs_to :cert_store
  belongs_to :user_group

  validates :NetworkId, :user_store_id, :cert_store_id, presence: true

end

app/models/teics_audit_log.rb
class TeicsAuditLog < ActiveRecord::Base
end

app/models/user.rb
class User < SecondBase::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :rememberable, :validatable, :authentication_keys => [:username]

  belongs_to :user_group
  has_many :member_groups

  validates :username, presence: true


end

app/models/user_group.rb
class UserGroup < SecondBase::Base
  acts_as_paranoid

  has_many :member_groups
  has_many :users
  has_many :cert_store_roles
  has_many :cert_stores
  has_many :cert_source_links
  has_many :environments
  has_many :identity_types
  has_many :sources
  has_many :source_links
  has_many :roles
  has_many :user_source_links
  has_many :user_store_roles
  has_many :user_stores
  has_many :store_accesses

  validates :UserGroupName, presence: true

end

app/models/user_source_link.rb
class UserSourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source_link
  belongs_to :user_store
  belongs_to :user_group

end

app/models/user_store.rb
class UserStore < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source
  belongs_to :environment
  belongs_to :identity_type
  belongs_to :user_group
  has_many :user_source_links
  has_many :user_store_roles

  validates :UserStoreName, :UserStorePassword, :UserStoreExpirationDate, :source_id, :environment_id, :identity_type_id, presence: true

end

app/models/user_store_role.rb
class UserStoreRole < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role
  belongs_to :user_store
  belongs_to :user_group

end

app/controllers/identity_types_controller.rb
class IdentityTypesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_identity_type, only: [:show, :edit, :update, :destroy]

  # GET /identity_types
  # GET /identity_types.json
  def index
    @identity_types = IdentityType.all
  end

  # GET /identity_types/1
  # GET /identity_types/1.json
  def show
  end

  # GET /identity_types/new
  def new
    @identity_type = IdentityType.new
    authorize @identity_type
  end

  # GET /identity_types/1/edit
  def edit
  end

  # POST /identity_types
  # POST /identity_types.json
  def create
    @identity_type = IdentityType.new(identity_type_params)

    respond_to do |format|
      authorize @identity_type

      if @identity_type.save
        format.html { redirect_to @identity_type, notice: 'Identity type was successfully created.' }
        format.json { render :show, status: :created, location: @identity_type }
      else
        format.html { render :new }
        format.json { render json: @identity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /identity_types/1
  # PATCH/PUT /identity_types/1.json
  def update
    respond_to do |format|
      authorize @identity_type

      if @identity_type.update(identity_type_params)
        format.html { redirect_to @identity_type, notice: 'Identity type was successfully updated.' }
        format.json { render :show, status: :ok, location: @identity_type }
      else
        format.html { render :edit }
        format.json { render json: @identity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identity_types/1
  # DELETE /identity_types/1.json
  def destroy
    @identity_type.destroy
    respond_to do |format|
      authorize @identity_type

      format.html { redirect_to identity_types_url, notice: 'Identity type was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_identity_type
      @identity_type = IdentityType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def identity_type_params
      params.require(:identity_type).permit(:IdentityTypeName, :IdentityTypeDescription, :CreatedBy, :CreatedDate, :LastModifiedBy, :LastModifiedDate, :IsDeleted)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/identity_types_helper.rb
module IdentityTypesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/identity_types/_form.html.erb
<%= form_for(@identity_type) do |f| %>
  <% if @identity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@identity_type.errors.count, "error") %> prohibited this identity_type from being saved:</h2>

      <ul>
      <% @identity_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'Identity Type Name' %><br>
    <%= f.text_area :IdentityTypeName, :cols => "40", :rows => "0" %>
  </div>
  <div class="field">
    <%= f.label :'Identity Type Description' %><br>
    <%= f.text_area :IdentityTypeDescription, :cols => "40", :rows => "5" %>
  </div>
  <div class="field">
    <%= f.label :'Created By' %><br>
    <%= f.text_field :CreatedBy %>
  </div>
  <div class="field">
    <%= f.label :'Created Date' %><br>
    <%= f.datetime_select :CreatedDate %>
  </div>
  <div class="field">
    <%= f.label :'Last Modified By' %><br>
    <%= f.text_field :LastModifiedBy %>
  </div>
  <div class="field">
    <%= f.label :'Last Modified Date' %><br>
    <%= f.datetime_select :LastModifiedDate %>
  </div>
  <div class="field">
    <%= f.label :'Is Deleted' %><br>
    <%= f.check_box :IsDeleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/identity_types/edit.html.erb
<h1>Updating Identity Type</h1>

<%= form_for(@identity_type) do |f| %>
    <% if @identity_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@identity_type.errors.count, "error") %> prohibited this identity_type from being saved:</h2>

          <ul>
            <% @identity_type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'Identity Type Name' %><br>
      <%= f.text_area :IdentityTypeName, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'Identity Type Description' %><br>
      <%= f.text_area :IdentityTypeDescription, :cols => "40", :rows => "5" %>
    </div>
    <div class="field">
      <%= f.label :'Last Modified By' %><br>
      <%= f.text_field :LastModifiedBy %>
    </div>
    <div class="field">
      <%= f.label :'Last Modified Date' %><br>
      <%= f.datetime_select :LastModifiedDate %>
    </div>
    <div class="field">
      <%= f.label :'Is Deleted' %><br>
      <%= f.check_box :IsDeleted %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'View Details', @identity_type %> |
<%= link_to 'Back', identity_types_path %>

app/views/identity_types/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>


<h1>Identity Types</h1>

<div style="overflow-x:auto;">
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      text-align: center;
      padding: 8px;
    }

    tr:nth-child(even){background-color: #f2f2f2}
  </style>

  <BR>

  <table>
    <thead>
    <tr>
      <th>Identity Type Name</th>
      <th>Identity Type Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>


    <tbody>
    <% @identity_types.each do |identity_type| %>
        <tr>
          <td><%= identity_type.IdentityTypeName %></td>
          <td><%= identity_type.IdentityTypeDescription %></td>
          <td><%= link_to 'View Details', identity_type %></td>


          <% if policy(identity_type).update? %>
              <td><%= link_to 'Update', edit_identity_type_path(identity_type) %></td>
          <% end %>

          <% if policy(identity_type).destroy? %>
              <td><%= link_to 'Delete', identity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

          <% if policy(identity_type).new? %>
              <td><%= link_to 'Create New Identity Type', new_identity_type_path(identity_type) %></td>
          <% end %>

        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/identity_types/new.html.erb
<h1>New Identity Type</h1>

<%= form_for(@identity_type) do |f| %>
    <% if @identity_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@identity_type.errors.count, "error") %> prohibited this identity_type from being saved:</h2>

          <ul>
            <% @identity_type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'Identity Type Name' %><br>
      <%= f.text_area :IdentityTypeName, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'Identity Type Description' %><br>
      <%= f.text_area :IdentityTypeDescription, :cols => "40", :rows => "5" %>
    </div>
    <div class="field">
      <%= f.label :'Created By' %><br>
      <%= f.text_field :CreatedBy %>
    </div>
    <div class="field">
      <%= f.label :'Created Date' %><br>
      <%= f.datetime_select :CreatedDate %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Back', identity_types_path %>

app/views/identity_types/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>Identity Type Name:</strong>
  <%= @identity_type.IdentityTypeName %>
</p>

<p>
  <strong>Identity Type Description:</strong>
  <%= @identity_type.IdentityTypeDescription %>
</p>
  </div>
  </div>

<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>Created By:</strong>
  <%= @identity_type.CreatedBy %>
</p>

<p>
  <strong>Created Date:</strong>
  <%= @identity_type.CreatedDate %>
</p>

<p>
  <strong>Last Modified By:</strong>
  <%= @identity_type.LastModifiedBy %>
</p>

<p>
  <strong>Last Modified Date:</strong>
  <%= @identity_type.LastModifiedDate %>
</p>

  </div>
  </div>

<%= link_to 'Back', identity_types_path %>