config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:email',     to: 'users#show',       via: 'get'

  resources :member_groups
  resources :user_groups
  resources :user_access_audit_logs
  resources :teics_audit_logs
  resources :roles
  resources :store_accesses
  resources :cert_source_links
  resources :user_source_links
  resources :user_store_roles
  resources :cert_store_roles
  resources :user_stores
  resources :cert_stores
  resources :identity_types
  resources :environments
  resources :source_links
  resources :sources
  resources :home
  resources :welcome

   root 'home#index'

end

app/models/cert_source_link.rb
class CertSourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source_link
  belongs_to :cert_store
  belongs_to :user_group

end

app/models/cert_store.rb
class CertStore < ActiveRecord::Base
  mount_uploader :unc, UncUploader
  acts_as_paranoid

  belongs_to :source
  belongs_to :environment
  belongs_to :identity_type
  belongs_to :user_group
  has_many :cert_source_links
  has_many :cert_store_roles

  validates :CertStoreName, :CertStoreDescription, :CertStorePassword, :CertStoreExpirationDate, :unc, :MimeType, :source_id, :environment_id, :identity_type_id, presence: true

  accepts_nested_attributes_for :cert_source_links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :cert_store_roles, reject_if: :all_blank, allow_destroy: true


end

app/models/cert_store_role.rb
class CertStoreRole < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role
  belongs_to :cert_store
  belongs_to :user_group

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :EnvironmentName, :EnvironmentDescription, presence: true

end

app/models/identity_type.rb
class IdentityType < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :IdentityTypeName, :IdentityTypeDescription, presence: true

end

app/models/member_group.rb
class MemberGroup < SecondBase::Base
  acts_as_paranoid

  belongs_to :user_group
  belongs_to :user

end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source
  belongs_to :user_group
  has_many :cert_store_roles
  has_many :user_store_roles

  validates :RoleDescription, :source_id, presence: true

end

app/models/source.rb
class Source < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :SourceDescription, presence: true

end

app/models/source_link.rb
class SourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_source_links
  has_many :user_source_links

  validates :Hyperlink, presence: true

end

app/models/store_access.rb
class StoreAccess < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_store
  belongs_to :cert_store
  belongs_to :user_group

  validates :NetworkId, :user_store_id, :cert_store_id, presence: true

end

app/models/teics_audit_log.rb
class TeicsAuditLog < ActiveRecord::Base
end

app/models/user.rb
class User < SecondBase::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :rememberable, :validatable, :authentication_keys => [:username]

  belongs_to :user_group
  has_many :member_groups

  validates :username, presence: true


end

app/models/user_group.rb
class UserGroup < SecondBase::Base
  acts_as_paranoid

  has_many :member_groups
  has_many :users
  has_many :cert_store_roles
  has_many :cert_stores
  has_many :cert_source_links
  has_many :environments
  has_many :identity_types
  has_many :sources
  has_many :source_links
  has_many :roles
  has_many :user_source_links
  has_many :user_store_roles
  has_many :user_stores
  has_many :store_accesses

  validates :UserGroupName, presence: true

end

app/models/user_source_link.rb
class UserSourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source_link
  belongs_to :user_store
  belongs_to :user_group

end

app/models/user_store.rb
class UserStore < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source
  belongs_to :environment
  belongs_to :identity_type
  belongs_to :user_group
  has_many :user_source_links
  has_many :user_store_roles

  validates :UserStoreName, :UserStorePassword, :UserStoreExpirationDate, :source_id, :environment_id, :identity_type_id, presence: true

end

app/models/user_store_role.rb
class UserStoreRole < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role
  belongs_to :user_store
  belongs_to :user_group

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
    authorize @user_group
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      authorize @user_group

      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      authorize @user_group

      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      authorize @user_group

      format.html { redirect_to user_groups_url, notice: 'User group was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:UserGroupName, :CreatedBy, :CreatedDate, :LastModifiedBy, :LastModifiedDate, :IsDeleted)
    end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'User Group Name' %><br>
    <%= f.text_area :UserGroupName, :cols => "40", :rows => "0" %>
  </div>
    <div class="field">
      <%= f.label :'Admin?' %><br>
      <%= f.check_box :admin %>
    </div>
  <div class="field">
    <%= f.label :'Created By' %><br>
    <%= f.text_field :CreatedBy %>
  </div>
  <div class="field">
    <%= f.label :'Created Date' %><br>
    <%= f.datetime_select :CreatedDate %>
  </div>
  <div class="field">
    <%= f.label :'Last Modified By' %><br>
    <%= f.text_field :LastModifiedBy %>
  </div>
  <div class="field">
    <%= f.label :'Last Modified Date' %><br>
    <%= f.datetime_select :LastModifiedDate %>
  </div>
  <div class="field">
    <%= f.label :'Is Deleted' %><br>
    <%= f.check_box :IsDeleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Updating User Group</h1>

<%= form_for(@user_group) do |f| %>
    <% if @user_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

          <ul>
            <% @user_group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'User Group Name' %><br>
      <%= f.text_area :UserGroupName, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'Admin?' %><br>
      <%= f.check_box :admin %>
    </div>
    <div class="field">
      <%= f.label :'Last Modified By' %><br>
      <%= f.text_field :LastModifiedBy %>
    </div>
    <div class="field">
      <%= f.label :'Last Modified Date' %><br>
      <%= f.datetime_select :LastModifiedDate %>
    </div>
    <div class="field">
      <%= f.label :'Is Deleted' %><br>
      <%= f.check_box :IsDeleted %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'View Details', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>


<h1>User Groups</h1>

<div style="overflow-x:auto;">
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      text-align: center;
      padding: 8px;
    }

    tr:nth-child(even){background-color: #f2f2f2}
  </style>


  <BR>

  <table>
    <thead>
    <tr>
      <th>User Group Name</th>
      <th>Admin?</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @user_groups.each do |user_group| %>
        <tr>
          <td><%= user_group.UserGroupName %></td>
          <td><%= user_group.admin %></td>
          <td><%= link_to 'View Details', user_group %></td>


          <% if policy(user_group).update? %>
              <td><%= link_to 'Update', edit_user_group_path(user_group) %></td>
          <% end %>

          <% if policy(user_group).destroy? %>
              <td><%= link_to 'Delete', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

          <% if policy(user_group).new? %>
              <td><%= link_to 'Create New User Group', new_user_group_path(user_group) %></td>
          <% end %>

        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= form_for(@user_group) do |f| %>
    <% if @user_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

          <ul>
            <% @user_group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'User Group Name' %><br>
      <%= f.text_area :UserGroupName, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'Admin?' %><br>
      <%= f.check_box :admin %>
    </div>
    <div class="field">
      <%= f.label :'Created By' %><br>
      <%= f.text_field :CreatedBy %>
    </div>
    <div class="field">
      <%= f.label :'Created Date' %><br>
      <%= f.datetime_select :CreatedDate %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>User Group Name:</strong>
  <%= @user_group.UserGroupName %>
</p>
    <p>
      <strong>Admin?</strong>
      <%= @user_group.admin %>
    </p>
  </div>
  </div>

<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>Created By:</strong>
  <%= @user_group.CreatedBy %>
</p>

<p>
  <strong>Created Date:</strong>
  <%= @user_group.CreatedDate %>
</p>

<p>
  <strong>Last Modified By:</strong>
  <%= @user_group.LastModifiedBy %>
</p>

<p>
  <strong>Last Modified Date:</strong>
  <%= @user_group.LastModifiedDate %>
</p>

  </div>
  </div>

<%= link_to 'Back', user_groups_path %>