config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:email',     to: 'users#show',       via: 'get'

  resources :member_groups
  resources :user_groups
  resources :user_access_audit_logs
  resources :teics_audit_logs
  resources :roles
  resources :store_accesses
  resources :cert_source_links
  resources :user_source_links
  resources :user_store_roles
  resources :cert_store_roles
  resources :user_stores
  resources :cert_stores
  resources :identity_types
  resources :environments
  resources :source_links
  resources :sources
  resources :home
  resources :welcome

   root 'home#index'

end

app/models/cert_source_link.rb
class CertSourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source_link
  belongs_to :cert_store
  belongs_to :user_group

end

app/models/cert_store.rb
class CertStore < ActiveRecord::Base
  mount_uploader :unc, UncUploader
  acts_as_paranoid

  belongs_to :source
  belongs_to :environment
  belongs_to :identity_type
  belongs_to :user_group
  has_many :cert_source_links
  has_many :cert_store_roles

  validates :CertStoreName, :CertStoreDescription, :CertStorePassword, :CertStoreExpirationDate, :unc, :MimeType, :source_id, :environment_id, :identity_type_id, presence: true

  accepts_nested_attributes_for :cert_source_links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :cert_store_roles, reject_if: :all_blank, allow_destroy: true


end

app/models/cert_store_role.rb
class CertStoreRole < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role
  belongs_to :cert_store
  belongs_to :user_group

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :EnvironmentName, :EnvironmentDescription, presence: true

end

app/models/identity_type.rb
class IdentityType < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :IdentityTypeName, :IdentityTypeDescription, presence: true

end

app/models/member_group.rb
class MemberGroup < SecondBase::Base
  acts_as_paranoid

  belongs_to :user_group
  belongs_to :user

end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source
  belongs_to :user_group
  has_many :cert_store_roles
  has_many :user_store_roles

  validates :RoleDescription, :source_id, presence: true

end

app/models/source.rb
class Source < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_stores
  has_many :user_stores

  validates :SourceDescription, presence: true

end

app/models/source_link.rb
class SourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_group
  has_many :cert_source_links
  has_many :user_source_links

  validates :Hyperlink, presence: true

end

app/models/store_access.rb
class StoreAccess < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user_store
  belongs_to :cert_store
  belongs_to :user_group

  validates :NetworkId, :user_store_id, :cert_store_id, presence: true

end

app/models/teics_audit_log.rb
class TeicsAuditLog < ActiveRecord::Base
end

app/models/user.rb
class User < SecondBase::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :rememberable, :validatable, :authentication_keys => [:username]

  belongs_to :user_group
  has_many :member_groups

  validates :username, presence: true


end

app/models/user_group.rb
class UserGroup < SecondBase::Base
  acts_as_paranoid

  has_many :member_groups
  has_many :users
  has_many :cert_store_roles
  has_many :cert_stores
  has_many :cert_source_links
  has_many :environments
  has_many :identity_types
  has_many :sources
  has_many :source_links
  has_many :roles
  has_many :user_source_links
  has_many :user_store_roles
  has_many :user_stores
  has_many :store_accesses

  validates :UserGroupName, presence: true

end

app/models/user_source_link.rb
class UserSourceLink < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source_link
  belongs_to :user_store
  belongs_to :user_group

end

app/models/user_store.rb
class UserStore < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :source
  belongs_to :environment
  belongs_to :identity_type
  belongs_to :user_group
  has_many :user_source_links
  has_many :user_store_roles

  validates :UserStoreName, :UserStorePassword, :UserStoreExpirationDate, :source_id, :environment_id, :identity_type_id, presence: true

end

app/models/user_store_role.rb
class UserStoreRole < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :role
  belongs_to :user_store
  belongs_to :user_group

end

app/controllers/user_stores_controller.rb
class UserStoresController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user_store, only: [:show, :edit, :update, :destroy]

  # GET /user_stores
  # GET /user_stores.json
  def index
    @user_stores = UserStore.all
  end

  # GET /user_stores/1
  # GET /user_stores/1.json
  def show
  end

  # GET /user_stores/new
  def new
    @user_store = UserStore.new
    authorize @user_store
  end

  # GET /user_stores/1/edit
  def edit
  end

  # POST /user_stores
  # POST /user_stores.json
  def create
    @user_store = UserStore.new(user_store_params)

    respond_to do |format|
      authorize @user_store

      if @user_store.save
        format.html { redirect_to @user_store, notice: 'User store was successfully created.' }
        format.json { render :show, status: :created, location: @user_store }
      else
        format.html { render :new }
        format.json { render json: @user_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stores/1
  # PATCH/PUT /user_stores/1.json
  def update
    respond_to do |format|
      authorize @user_store

      if @user_store.update(user_store_params)
        format.html { redirect_to @user_store, notice: 'User store was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_store }
      else
        format.html { render :edit }
        format.json { render json: @user_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stores/1
  # DELETE /user_stores/1.json
  def destroy
    @user_store.destroy
    respond_to do |format|
      authorize @user_store

      format.html { redirect_to user_stores_url, notice: 'User store was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_store
      @user_store = UserStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_store_params
      params.require(:user_store).permit(:UserStoreName, :UserStorePassword, :UserStoreExpirationDate, :source_id, :environment_id, :identity_type_id, :CreatedBy, :CreatedDate, :LastModifiedBy, :LastModifiedDate, :IsDeleted)
    end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/user_stores_helper.rb
module UserStoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_stores/_form.html.erb
<%= form_for(@user_store) do |f| %>
  <% if @user_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_store.errors.count, "error") %> prohibited this user_store from being saved:</h2>

      <ul>
      <% @user_store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'User Store Name' %><br>
    <%= f.text_area :UserStoreName, :cols => "40", :rows => "0" %>
  </div>
  <div class="field">
    <%= f.label :'User Store Password' %><br>
    <%= f.text_area :UserStorePassword, :cols => "40", :rows => "0" %>
  </div>
  <div class="field">
    <%= f.label :'User Store Expiration Date' %><br>
    <%= f.datetime_select :UserStoreExpirationDate %>
  </div>
  <div class="field">
    <%= f.label :'Source Description' %><br>
    <%= f.collection_select :source_id, Source.all, :id, :SourceDescription, include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :'Environment Name' %><br>
    <%= f.collection_select :environment_id, Environment.all, :id, :EnvironmentName, include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :'Identity Type Name' %><br>
    <%= f.collection_select :identity_type_id, IdentityType.all, :id, :IdentityTypeName, include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :'Created By' %><br>
    <%= f.text_field :CreatedBy %>
  </div>
  <div class="field">
    <%= f.label :'Created Date' %><br>
    <%= f.datetime_select :CreatedDate %>
  </div>
  <div class="field">
    <%= f.label :'Last Modified By' %><br>
    <%= f.text_field :LastModifiedBy %>
  </div>
  <div class="field">
    <%= f.label :'Last Modified Date' %><br>
    <%= f.datetime_select :LastModifiedDate %>
  </div>
  <div class="field">
    <%= f.label :'Is Deleted' %><br>
    <%= f.check_box :IsDeleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_stores/edit.html.erb
<h1>Updating User Store</h1>

<%= form_for(@user_store) do |f| %>
    <% if @user_store.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_store.errors.count, "error") %> prohibited this user_store from being saved:</h2>

          <ul>
            <% @user_store.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'User Store Name' %><br>
      <%= f.text_area :UserStoreName, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'User Store Password' %><br>
      <%= f.text_area :UserStorePassword, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'User Store Expiration Date' %><br>
      <%= f.datetime_select :UserStoreExpirationDate %>
    </div>
    <div class="field">
      <%= f.label :'Source Description' %><br>
      <%= f.collection_select :source_id, Source.all, :id, :SourceDescription, include_blank:true %>
    </div>
    <div class="field">
      <%= f.label :'Environment Name' %><br>
      <%= f.collection_select :environment_id, Environment.all, :id, :EnvironmentName, include_blank:true %>
    </div>
    <div class="field">
      <%= f.label :'Identity Type Name' %><br>
      <%= f.collection_select :identity_type_id, IdentityType.all, :id, :IdentityTypeName, include_blank:true %>
    </div>
    <div class="field">
      <%= f.label :'Last Modified By' %><br>
      <%= f.text_field :LastModifiedBy %>
    </div>
    <div class="field">
      <%= f.label :'Last Modified Date' %><br>
      <%= f.datetime_select :LastModifiedDate %>
    </div>
    <div class="field">
      <%= f.label :'Is Deleted' %><br>
      <%= f.check_box :IsDeleted %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'View Details', @user_store %> |
<%= link_to 'Back', user_stores_path %>

app/views/user_stores/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>


<h1>User Store</h1>

<div style="overflow-x:auto;">
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      text-align: center;
      padding: 8px;
    }

    tr:nth-child(even){background-color: #f2f2f2}
  </style>


  <BR>

  <table>
    <thead>
    <tr>
      <th>User Store Name</th>
      <th>User Store Expiration Date</th>
      <th>Source Description</th>
      <th>Environment Name</th>
      <th>Identity Type Name</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @user_stores.each do |user_store| %>
        <tr>
          <td><%= user_store.UserStoreName %></td>
          <td><%= user_store.UserStoreExpirationDate %></td>
          <td><%= user_store.source.SourceDescription %></td>
          <td><%= user_store.environment.EnvironmentName %></td>
          <td><%= user_store.identity_type.IdentityTypeName %></td>
          <td><%= link_to 'View Details', user_store %></td>

          <% if policy(user_store).update? %>
              <td><%= link_to 'Update', edit_user_store_path(user_store) %></td>
          <% end %>

          <% if policy(user_store).destroy? %>
              <td><%= link_to 'Delete', user_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

          <% if policy(user_store).new? %>
              <td><%= link_to 'Create New User Store', new_user_store_path(user_store) %></td>
          <% end %>


        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/user_stores/new.html.erb
<h1>New User Store</h1>

<%= form_for(@user_store) do |f| %>
    <% if @user_store.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_store.errors.count, "error") %> prohibited this user_store from being saved:</h2>

          <ul>
            <% @user_store.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :'User Store Name' %><br>
      <%= f.text_area :UserStoreName, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'User Store Password' %><br>
      <%= f.text_area :UserStorePassword, :cols => "40", :rows => "0" %>
    </div>
    <div class="field">
      <%= f.label :'User Store Expiration Date' %><br>
      <%= f.datetime_select :UserStoreExpirationDate %>
    </div>
    <div class="field">
      <%= f.label :'Source Description' %><br>
      <%= f.collection_select :source_id, Source.all, :id, :SourceDescription, include_blank:true %>
    </div>
    <div class="field">
      <%= f.label :'Environment Name' %><br>
      <%= f.collection_select :environment_id, Environment.all, :id, :EnvironmentName, include_blank:true %>
    </div>
    <div class="field">
      <%= f.label :'Identity Type Name' %><br>
      <%= f.collection_select :identity_type_id, IdentityType.all, :id, :IdentityTypeName, include_blank:true %>
    </div>
    <div class="field">
      <%= f.label :'Created By' %><br>
      <%= f.text_field :CreatedBy %>
    </div>
    <div class="field">
      <%= f.label :'Created Date' %><br>
      <%= f.datetime_select :CreatedDate %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', user_stores_path %>

app/views/user_stores/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>User Store Name:</strong>
  <%= @user_store.UserStoreName %>
</p>

    <div class="panel panel-default">
      <div class="panel-body">
<p>
  <strong>User Store Password:</strong>
  <%= @user_store.UserStorePassword %>
</p>

<p>
  <strong>User Store Expiration Date:</strong>
  <%= @user_store.UserStoreExpirationDate %>
</p>
</div>
      </div>

<p>
  <strong>Source Description:</strong>
  <%= @user_store.source.SourceDescription %>
</p>

<p>
  <strong>Environment Name:</strong>
  <%= @user_store.environment.EnvironmentName %>
</p>

<p>
  <strong>Identity Type Name:</strong>
  <%= @user_store.identity_type.IdentityTypeName %>
</p>
  </div>
  </div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">User Store Source Links</h3>
  </div>
  <div class="panel-body">

    <div style="overflow-x:auto;">
      <style>
        table {
          border-collapse: collapse;
          width: 100%;
        }

        th, td {
          text-align: center;
          padding: 8px;
        }

        tr:nth-child(even){background-color: #f2f2f2}
      </style>

      <a class="btn btn-primary btn-sm" href="http://localhost:3000/source_links/new" role="button">Add Source Link</a>
      <BR><BR>

      <table>
        <thead>
        <tr>
          <th>Hyperlink</th>
          <th colspan="3"></th>
        </tr>
        </thead>



        <tbody>
        <% @user_store.user_source_links.each do |user_source_link| %>
            <tr>
              <td><%= user_source_link.source_link.Hyperlink %></td>
              <td><%= link_to 'View Details', user_source_link %></td>

              <% if policy(user_source_link).update? %>
                  <td><%= link_to 'Update', edit_user_source_link_path(user_source_link) %></td>
              <% end %>

              <% if policy(user_source_link).destroy? %>
                  <td><%= link_to 'Delete', user_source_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>

            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <br>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">User Store Roles</h3>
  </div>
  <div class="panel-body">

    <div style="overflow-x:auto;">
      <style>
        table {
          border-collapse: collapse;
          width: 100%;
        }

        th, td {
          text-align: center;
          padding: 8px;
        }

        tr:nth-child(even){background-color: #f2f2f2}
      </style>

      <a class="btn btn-primary btn-sm" href="http://localhost:3000/roles/new" role="button">Add Role</a>
      <BR><BR>

      <table>
        <thead>
        <tr>
          <th>Role Description</th>
          <th colspan="3"></th>
        </tr>
        </thead>



        <tbody>
        <% @user_store.user_store_roles.each do |user_store_role| %>
            <tr>
              <td><%= user_store_role.role.RoleDescription %></td>
              <td><%= link_to 'View Details', user_store_role %></td>

              <% if policy(user_store_role).update? %>
                  <td><%= link_to 'Update', edit_user_store_role_path(user_store_role) %></td>
              <% end %>

              <% if policy(user_store_role).destroy? %>
                  <td><%= link_to 'Delete', user_store_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>

            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <br>
  </div>

</div>

<div class="panel panel-default">
  <div class="panel-body">
    <p>
      <strong>Created By:</strong>
      <%= @user_store.CreatedBy %>
    </p>

    <p>
      <strong>Created Date:</strong>
      <%= @user_store.CreatedDate %>
    </p>

    <p>
      <strong>Last Modified By:</strong>
      <%= @user_store.LastModifiedBy %>
    </p>

    <p>
      <strong>Last Modified Date:</strong>
      <%= @user_store.LastModifiedDate %>
    </p>

  </div>
</div>


<%= link_to 'Back', user_stores_path %>